server:
  port: 9098

spring:
  application:
    name: ORDER-SERVICE
  zipkin:
    base-url: http://zipkin:9411/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: order-service
