server:
  port: 9002

spring:
  application:
    name: ADDRESS-SERVICE
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  zipkin:
    base-url: http://zipkin:9411/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: address-service



